---
title: "Birnbaum-Saunders Reparametrizada"
output: html_document
---

Código reproduzido dos autores:

LEÃO, Jeremias; LEIVA, Víctor; SAULO, Helton; TOMAZELLA, Vera. A survival model with Birnbaum–Saunders frailty for uncensored and censored cancer data. Brazilian Journal of Probability and Statistics, v. 32, n. 4, p. 707–729, 2018. DOI: 10.1214/17-BJPS360.

```{r}

options(warn = -1)
```

```{r}

install.packages(
  "https://cran.r-project.org/src/contrib/Archive/gbs/gbs_1.0.tar.gz",
  repos = NULL,
  type = "source"
)
```

```{r}

library(MASS)
library(survival)
library(gbs)
library(stats)
library(stats4)
library(boot)
library(locfit)
library(flexsurv)
library(numDeriv)
library(lattice)
library(HSAUR)

```

```{r}


##################################################################
##################################################################
# Estimation of parameters in BS Frailty model
# with Exponential baseline distribution
##################################################################
##################################################################

##################################################################
## Unconditional Survival Function of the BS frailty model
##################################################################

uncsurv_BS <- function(t,delta,lambda){
  st <- (exp( (delta/2)*( 1 - sqrt((delta+4*lambda*t+1)/(delta+1)) ) )*(sqrt(delta+1) + sqrt((delta+4*lambda*t+1)) ))/(2*sqrt(delta+4*lambda*t+1))
  
  return(st)
}
```

```{r}

##################################################################
## Unconditional Hazard Function of the BS frailty model
##################################################################

unchazd_BS <- function(t,delta,lambda){
  
  ht <- lambda*( delta*( delta + sqrt( (delta+1)*(delta+4*lambda*t+1) ) + 4*lambda*t + 3 ) + 2 )/( (delta+4*lambda*t+1)*( delta + sqrt( (delta+1)*(delta+4*lambda*t+1) ) + 1) )
  
  return(ht)
  
}
```

```{r}

##################################################################
## Log Likelihood Function of BS Frailty Model (Exp - baseline)
##################################################################

log.lik_BS <- function(par,x,cens){
  
  delta   <- par[1]
  lambda  <- par[2]
  
  loglik <- sum( cens*log( unchazd_BS(t=x,delta=delta,lambda=lambda) ) ) + sum( log( uncsurv_BS(t=x,delta=delta,lambda=lambda) ) )
  
  return (-loglik)
}

log.lik_BSHE <- function(par,y,cens){
  
  delta   <- par[1]
  lambda  <- par[2]
  
  loglik <- sum( cens*log( unchazd_BS(t=y,delta=delta,lambda=lambda) ) ) + sum( log( uncsurv_BS(t=y,delta=delta,lambda=lambda) ) )
  
  return (loglik)
}

```

```{r}

##################################################################
##################################################################
# Estimation of parameters in BS Frailty model
# with Weibull baseline distribution
##################################################################
##################################################################

##################################################################
# # Cumulative Hazard Rate baseline - Weibull
##################################################################

CHR_base <- function(t,alpha,eta){
  
  chr <- (t/alpha)^eta
  
  return(chr)
}
```

```{r}

##################################################################
# Hazard Rate baseline - Weibull
##################################################################

HR_base <- function(t,alpha,eta){
  
  hr <- (eta*(t^(eta-1)))/(alpha^eta)
  return(hr)
}
```

```{r}

##################################################################
# Unconditional survival
# function of BS frailty
##################################################################

unc_sf <- function(t,alpha,eta,delta){
  
  a <- sqrt(delta+4*CHR_base(t,alpha,eta)+1)
  b <- (delta/2)*(1 - (a/sqrt(delta+1)) )
  c <- a + sqrt(delta + 1)
  
  usf <- (exp(b)*c)/(2*a)
  
  return(usf)
  
}
```

```{r}

###################################
# Unconditional hazard
# rate of BS frailty
###################################

unc_hz <- function(t,alpha,eta,delta){
  
  a <- delta*(delta + sqrt( (delta+4*CHR_base(t,alpha,eta)+1)*(delta+1) ) + 4*CHR_base(t,alpha,eta) + 3) + 2
  b <- (delta + sqrt( (delta+4*CHR_base(t,alpha,eta)+1)*(delta+1) ) + 1)
  
  uhr <- ( (HR_base(t,alpha,eta))*a )/ ( (delta+4*CHR_base(t,alpha,eta)+1)*b )
  
  return(uhr)
  
}
```

```{r}

####################################################
# Log Likelihood Function of BS Frailty Model
####################################################

log.lik_BS_weibull <- function(par,x,cens){
  
  alpha  <- par[1]
  eta    <- par[2]
  delta  <- par[3]
  
  
  loglik <- sum( log( unc_sf(t=x,alpha=alpha,eta=eta,delta=delta) ) ) + sum( cens*log( unc_hz(t=x,alpha=alpha,eta=eta,delta=delta) ) )
  
  return (-loglik)
}

log.lik_BS_weibullHE <- function(par,y,cens){
  
  alpha  <- par[1]
  eta    <- par[2]
  delta  <- par[3]
  
  
  loglik <- sum( log( unc_sf(t=y,alpha=alpha,eta=eta,delta=delta) ) ) + sum( cens*log( unc_hz(t=y,alpha=alpha,eta=eta,delta=delta) ) )
  
  return (loglik)
}
```

```{r}

##################################################################
##################################################################


##################################################################
# Unconditional survival
# function of BS frailty - Log-Normal
##################################################################

unc_sf_logn <- function(t,delta,pmu,psig){
  
  a <- sqrt(delta+4*Hlnorm(t, meanlog=pmu, sdlog=psig, log=FALSE)+1)
  b <- (delta/2)*(1 - (a/sqrt(delta+1)) )
  c <- a + sqrt(delta + 1)
  
  usf <- (exp(b)*c)/(2*a)
  
  return(usf)
  
}
```

```{r}

##################################################################
# Unconditional hazard
# rate of BS frailty
##################################################################

unc_hz_logn <- function(t,delta,pmu,psig){
  
  a <- delta*(delta + sqrt( (delta+4*Hlnorm(x=t, meanlog=pmu, sdlog=psig, log=FALSE)+1)*(delta+1) ) + 4*Hlnorm(x=t, meanlog=pmu, sdlog=psig, log=FALSE) + 3) + 2
  b <- (delta + sqrt( (delta+4*Hlnorm(x=t, meanlog=pmu, sdlog=psig, log=FALSE)+1)*(delta+1) ) + 1)
  
  uhr <- ( (hlnorm(x=t, meanlog=pmu, sdlog=psig, log=FALSE))*a )/ ( (delta+4*Hlnorm(x=t, meanlog=pmu, sdlog=psig, log=FALSE)+1)*b )
  
  return(uhr)
  
}
```

```{r}


####################################################
# Log Likelihood Function of BS Frailty Model
####################################################

log.lik_BS_logn <- function(par,x,cens){
  
  delta  <- par[1]
  pmu    <- par[2]
  psig   <- par[3]
  
  
  loglik <- sum( log( unc_sf_logn(t=x,delta=delta,pmu=pmu,psig=psig) ) ) + sum( cens*log( unc_hz_logn(t=x,delta=delta,pmu=pmu,psig=psig) ) )
  
  return (-loglik)
}

log.lik_BS_lognHLN <- function(par,y,cens){
  
  alpha  <- par[1]
  eta    <- par[2]
  delta  <- par[3]
  
  
  loglik <- sum( log( unc_sf(t=y,alpha=alpha,eta=eta,delta=delta) ) ) + sum( cens*log( unc_hz(t=y,alpha=alpha,eta=eta,delta=delta) ) )
  
  return (loglik)
}

```

```{r}

# Reading Data Application 2  

data("cancer",package="survival")

times = veteran$time
status = veteran$status

```

```{r}

## 1
# Estimating parameter values of BS frailty Exponential
esti_BS <- mlebs(times)
chuteDelta  <- 2/(esti_BS$alphabsEstimate^2);chuteDelta
chuteLambda <- fitdistr(times,densfun="exponential")
chuteLambda <- as.numeric(chuteLambda$estimate[1]);chuteLambda

# Obtaining the results
est_BS   <- optim(c(chuteDelta,chuteLambda),log.lik_BS,x=times,method="CG",cens=status)
hatdelta  <- est_BS$par[1];hatdelta
hatlambda <- est_BS$par[2];hatlambda

# Estimated frailty variance
vnu1 <-(2*hatdelta+5)/(hatdelta+1)^2;vnu1

# AIC and BIC
aic1_BS <-    -2*(-log.lik_BS(c(hatdelta,hatlambda),times,status)) + 2*2;aic1_BS
bic1_BS <-    -2*(-log.lik_BS(c(hatdelta,hatlambda),times,status)) + 2*log(length(times));bic1_BS

-log.lik_BS(c(hatdelta,hatlambda),times,status)

## SEs  
valueH    <- -hessian(func=log.lik_BSHE,x=c(hatdelta,hatlambda),y=times,cens=status)
Hess      <- solve(valueH)
SE        <- sqrt(diag(Hess))

se.coef = SE
tval = est_BS$par/se.coef
matcoef = cbind(c(est_BS$par), se.coef, tval, 2*(1-pnorm(abs(tval))))
dimnames(matcoef) = list(names(tval), c(" Estimate",
                                        " Std. Error", " t value", "Pr(>|t|)"))
cat("\nCoefficient(s):\n")
printCoefmat(matcoef, digits = 6, signif.stars = TRUE) 
```

```{r}

## 2
# Estimatin parameter values of BS frailty Weibul
esti_BS     <- mlebs(times)
chuteDelta  <- 2/(esti_BS$alphabsEstimate^2);chuteDelta
chutealpha  <- 8.0
chuteeta    <- 2.0

# Obtaining the results
est_BS_Weibull <- optim(c(chutealpha,chuteeta,chuteDelta),log.lik_BS_weibull,x=times,method="BFGS",cens=status)
hatalpha_BS_wei       <- est_BS_Weibull$par[1];hatalpha_BS_wei
hateta_BS_wei         <- est_BS_Weibull$par[2];hateta_BS_wei
hatdelta_BS_wei       <- est_BS_Weibull$par[3];hatdelta_BS_wei

# Estimated frailty variance
vnu2 <-(2*hatdelta_BS_wei+5)/(hatdelta_BS_wei+1)^2;vnu2

# AIC and BIC
aic1_BS_wei <-    -2*(-log.lik_BS_weibull(c(hatalpha_BS_wei,hateta_BS_wei,hatdelta_BS_wei),times,status)) + 2*3;aic1_BS_wei
bic1_BS_wei <-    -2*(-log.lik_BS_weibull(c(hatalpha_BS_wei,hateta_BS_wei,hatdelta_BS_wei),times,status)) + 3*log(length(times));bic1_BS_wei

-log.lik_BS_weibull(c(hatalpha_BS_wei,hateta_BS_wei,hatdelta_BS_wei),times,status)

## SEs  
valueH    <- -hessian(func=log.lik_BS_weibullHE,x=c(hatalpha_BS_wei,hateta_BS_wei,hatdelta_BS_wei),y=times,cens=status)
Hess      <- solve(valueH)
SE        <- sqrt(diag(Hess))

se.coef = SE
tval = est_BS_Weibull$par/se.coef
matcoef = cbind(c(est_BS_Weibull$par), se.coef, tval, 2*(1-pnorm(abs(tval))))
dimnames(matcoef) = list(names(tval), c(" Estimate",
                                        " Std. Error", " t value", "Pr(>|t|)"))
cat("\nCoefficient(s):\n")
printCoefmat(matcoef, digits = 6, signif.stars = TRUE)  
```

```{r}

# exponencial
SFhat1 <- uncsurv_BS(t=times,delta=hatdelta,lambda=hatlambda)
DSresidualModel1 <- qnorm(SFhat1) 

# weibull
SFhat2 <- unc_sf(t=times,alpha=hatalpha_BS_wei,eta=hateta_BS_wei,delta=hatdelta_BS_wei)
DSresidualModel2 <- qnorm(SFhat2)
```

```{r}

# exponencial
SFhat1 <- uncsurv_BS(t=times,delta=hatdelta,lambda=hatlambda)
CSresidualModel1 <- -log(SFhat1)

# weibull
SFhat2 <- unc_sf(t=times,alpha=hatalpha_BS_wei,eta=hateta_BS_wei,delta=hatdelta_BS_wei)
CSresidualModel2 <- -log(SFhat2)
```

```{r}

envelopeDS <- function(x){
  U	         <- x
  n	         <- length(x)
  d2s 	     <- sort(U)
  xq2 	     <- qnorm(ppoints(n))
  Xsim 	     <- matrix(0, 100, n)
  for(i in 1:100){
    u2       <- rnorm(n)
    Xsim[i,] <- u2
  }
  Xsim2      <- apply(Xsim, 1, sort)
  d21        <- matrix(0, n, 1)
  d22        <- matrix(0, n, 1)
  for(i in 1:n){
    d21[i]  <- quantile(Xsim2[i,], 0.025)
    d22[i]  <- quantile(Xsim2[i,], 0.975)
  }
  d2med      <- apply(Xsim2, 1, mean)
  fy         <- range(d2s, d21, d22)
  plot(xq2, d2s, xlab = quote("qe"),
       ylab = quote("qr"), 
       pch = 20, ylim = fy)
  par(new = T)
  plot(xq2, d21, type = "l", ylim = fy, xlab = "", ylab = "")
  par(new = T)
  plot(xq2, d2med, type = "l", ylim = fy, xlab = "", ylab = "")
  par(new = T)
  plot(xq2, d22, type = "l", ylim = fy, xlab = "", ylab = "")
}

envelopeCS <- function(x){
  U	         <- x
  n	         <- length(x)
  d2s 	     <- sort(U)
  xq2 	     <- qexp(ppoints(n))
  Xsim 	     <- matrix(0, 100, n)
  for(i in 1:100){
    u2       <- rexp(n)
    Xsim[i,] <- u2
  }
  Xsim2      <- apply(Xsim, 1, sort)
  d21        <- matrix(0, n, 1)
  d22        <- matrix(0, n, 1)
  for(i in 1:n){
    d21[i]  <- quantile(Xsim2[i,], 0.025)
    d22[i]  <- quantile(Xsim2[i,], 0.975)
  }
  d2med      <- apply(Xsim2, 1, mean)
  fy         <- range(d2s, d21, d22)
  plot(xq2, d2s, xlab = quote("qe"),
       ylab = quote("qr"), 
       pch = 20, ylim = fy)
  par(new = T)
  plot(xq2, d21, type = "l", ylim = fy, xlab = "", ylab = "")
  par(new = T)
  plot(xq2, d2med, type = "l", ylim = fy, xlab = "", ylab = "")
  par(new = T)
  plot(xq2, d22, type = "l", ylim = fy, xlab = "", ylab = "")
}

```

```{r}

# cs residual - exponencial
envelopeCS(CSresidualModel1)
```

```{r}

# cs residual - weibull
envelopeCS(CSresidualModel2)
```

```{r}

# ds residual - weibull
envelopeDS(DSresidualModel2)
```

```{r}

# ds residual - exponencial
envelopeDS(DSresidualModel1)
```
